builds:
  - binary: slacksearch
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archive:
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x64
    386: x86
    darwin: macos
  files:
    - LICENSE

brew:
  github:
    owner: 4d63
    name: homebrew-slacksearch
  commit_author:
    name: Leigh McCulloch
    email: leigh@mcchouse.com
  folder: Formula
  homepage: "https://4d63.com/slacksearch"
  description: Simple Slack search.
  test: |
    system "#{bin}/slacksearch"
  install: |
    bin.install "slacksearch"
